(value)});

// promise1.catch((error) => {console.log('recived error')});